context:
  name: durationpy
  version: "0.10"

package:
  name: ${{ name }}
  version: "${{ version }}"

build:
  noarch: python
  number: 1
  script:
    interpreter: nu
    content:
      - "${{ PYTHON }} -m pip install *.whl"

requirements:
  build:
    - nushell
  host:
    - python
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - durationpy

source:
  url: https://files.pythonhosted.org/packages/b0/0d/9feae160378a3553fa9a339b0e9c1a048e147a4127210e286ef18b730f03/durationpy-0.10-py3-none-any.whl
  sha256: 3b41e1b601234296b4fb368338fdcd3e13e0b4fb5b67345948f4f2bf9868b286

about:
  description: |
    conda packaging of [https://github.com/icholy/durationpy](https://github.com/icholy/durationpy)

    build by [https://github.com/trim21/pypi-feedstocks](https://github.com/trim21/pypi-feedstocks)

  homepage: https://github.com/icholy/durationpy
  repository: https://github.com/icholy/durationpy
