[project]
name = "pypi-feedstocks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "dprint-py==0.49.1.2",
  "pyyaml==6.0.2",
]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
pypi-feedstocks = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
rattler-build = ">=0.39.0,<0.40"
