[project]
name = "pypi-feedstocks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "dprint-py==0.49.1.2",
  "pyyaml==6.0.2",
]
