outputs:
  - build:
      noarch: python
      number: 0
      script:
        content:
          - PIP_NO_INDEX=false ${{ PYTHON }} -m pip install --no-deps ${{ name }}==${{
            version }}
        interpreter: nu
    context:
      name: durationpy
      version: "0.9"
    package:
      name: ${{ name }}
      version: ${{ version }}
    requirements:
      build:
        - nushell
      host:
        - python
        - pip
      run:
        - python
    tests:
      - python:
          imports:
            - durationpy
  - build:
      noarch: python
      number: 0
      script:
        content:
          - PIP_NO_INDEX=false ${{ PYTHON }} -m pip install --no-deps ${{ name }}==${{
            version }}
        interpreter: nu
    context:
      name: qbittorrent-api
      version: 2025.2.0
    package:
      name: ${{ name }}
      version: ${{ version }}
    requirements:
      build:
        - nushell
      host:
        - python
        - pip
      run:
        - python
        - requests
        - packaging
    tests:
      - python:
          imports:
            - qbittorrentapi
  - build:
      noarch: python
      number: 0
      script:
        content:
          - PIP_NO_INDEX=false ${{ PYTHON }} -m pip install --no-deps ${{ name }}==${{
            version }}
        interpreter: nu
    context:
      name: sslog
      version: 0.0.0a52
    package:
      name: ${{ name }}
      version: ${{ version }}
    requirements:
      build:
        - nushell
      host:
        - python
        - pip
      run:
        - python
        - structlog==25.1.0
    tests:
      - python:
          imports:
            - sslog
  - build:
      noarch: python
      number: 0
      script:
        content:
          - PIP_NO_INDEX=false ${{ PYTHON }} -m pip install --no-deps ${{ name }}==${{
            version }}
        interpreter: nu
    context:
      name: transmission-rpc
      version: 7.0.11
    package:
      name: ${{ name }}
      version: ${{ version }}
    requirements:
      build:
        - nushell
      host:
        - python
        - pip
      run:
        - python
        - requests
        - certifi
        - typing_extensions>=4.5.0
    tests:
      - python:
          imports:
            - transmission_rpc
