context:
  name: qbittorrent-api
  version: '2025.2.0'

package:
  name: ${{ name }}
  version: '${{ version }}'

build:
  noarch: python
  number: 0
  script:
    interpreter: nu
    content:
      - 'PIP_NO_INDEX=false ${{ PYTHON }} -m pip install --no-deps ${{ name }}==${{ version }}'

requirements:
  build:
    - nushell
  host:
    - python ==${{python}}
    - pip
  run:
    - python >=${{python}}
    - requests
    - packaging

tests:
  - python:
      imports:
        - qbittorrentapi
