context:
  name: qbittorrent-api
  version: "2025.11.1"

package:
  name: ${{ name }}
  version: "${{ version }}"

build:
  noarch: python
  number: 1
  script:
    interpreter: nu
    content:
      - "${{ PYTHON }} -m pip install *.whl"

requirements:
  build:
    - nushell
  host:
    - python>=3.9
    - pip
  run:
    - python >=3.9
    - requests >=2.16.0
    - urllib3 >=1.24.2
    - packaging

tests:
  - python:
      imports:
        - qbittorrentapi

source:
  url: https://files.pythonhosted.org/packages/57/1a/66cd2daf0aa7c6809e2ff664b28d81e3381575cb96a4fe2a1410a3823ad3/qbittorrent_api-2025.11.0-py3-none-any.whl
  sha256: 99f877df8e064f672624e6665bb79d4ceec3d3db8a00bf2fa2e8a6cd9241d2f6

about:
  description: |
    conda packaging of [https://github.com/rmartin16/qbittorrent-api](https://github.com/rmartin16/qbittorrent-api)

    build by [https://github.com/trim21/pypi-feedstocks](https://github.com/trim21/pypi-feedstocks)

  homepage: https://github.com/rmartin16/qbittorrent-api
  repository: https://github.com/rmartin16/qbittorrent-api
