context:
  name: qbittorrent-api
  version: "2025.5.0"

package:
  name: ${{ name }}
  version: "${{ version }}"

build:
  noarch: python
  number: 0
  script:
    interpreter: nu
    content:
      - "${{ PYTHON }} -m pip install *.whl"

requirements:
  build:
    - nushell
  host:
    - python>=3.9
    - pip
  run:
    - python >=3.9
    - requests >=2.16.0
    - urllib3 >=1.24.2
    - packaging

tests:
  - python:
      imports:
        - qbittorrentapi

source:
  url: https://files.pythonhosted.org/packages/ad/b8/e8b19b8ffe626b2355660d7cfc578e51e0aa045964f14305875ec976f427/qbittorrent_api-2025.5.0-py3-none-any.whl
  sha256: 44d98791c98cf422fbd86bc19f7475ba4ca604a7d2729551867ec79be85cf4cd
