context:
  name: qbittorrent-api
  version: "2025.4.0"

package:
  name: ${{ name }}
  version: "${{ version }}"

build:
  noarch: python
  number: 0
  script:
    interpreter: nu
    content:
      - "${{ PYTHON }} -m pip install *.whl"

requirements:
  build:
    - nushell
  host:
    - python ==${{python_build}}
    - pip
  run:
    - python >=3.9
    - requests >=2.16.0
    - urllib3 >=1.24.2
    - packaging

tests:
  - python:
      imports:
        - qbittorrentapi

source:
  url: https://files.pythonhosted.org/packages/72/2d/f83a60b39e4c81a42d9925b9c63910051d57c4df46c933181ff4a969fb96/qbittorrent_api-2025.4.0-py3-none-any.whl
  sha256: e8cf2b8c50be33f9e3c4845bffc4862a6d2d898ba18ff40da108e4edca8bf9d0
