context:
  name: qbittorrent-api
  version: "2025.4.1"

package:
  name: ${{ name }}
  version: "${{ version }}"

build:
  noarch: python
  number: 0
  script:
    interpreter: nu
    content:
      - "${{ PYTHON }} -m pip install *.whl"

requirements:
  build:
    - nushell
  host:
    - python ==${{python_build}}
    - pip
  run:
    - python >=3.9
    - requests >=2.16.0
    - urllib3 >=1.24.2
    - packaging

tests:
  - python:
      imports:
        - qbittorrentapi

source:
  url: https://files.pythonhosted.org/packages/af/98/c4762a4e79e89872b3241ba34968e9789d860fa0e216874a5a5694ee28c7/qbittorrent_api-2025.4.1-py3-none-any.whl
  sha256: 7cf93e0f6927b8b098a2361bcf1bb975d10869a1aeb804d59843c927ed1cfabb
