context:
  name: transmission-rpc
  version: "7.0.11"

package:
  name: ${{ name }}
  version: "${{ version }}"

build:
  noarch: python
  number: 1
  script:
    interpreter: nu
    content:
      - "${{ PYTHON }} -m pip install *.whl"

requirements:
  build:
    - nushell
  host:
    - python ==3.9
    - pip
  run:
    - python >=3.9

    - requests
    - certifi
    - typing_extensions>=4.5.0

tests:
  - python:
      imports:
        - transmission_rpc
