context:
  name: "valkey"
  version: "6.1.0"

package:
  name: "valkey-py"
  version: "${{ version }}"

source:
  url: https://files.pythonhosted.org/packages/79/b0/c4d47032bbda89cff7af99c0b096db9b9453b9f0c1e24cf027aa616be389/valkey-6.1.0-py3-none-any.whl
  sha256: cfe769edae894f74ac946eff1e93f7d7f466032c3030ba7e9d089a742459ac9c

build:
  noarch: python
  number: 1
  script:
    interpreter: nu
    content: "${{ PYTHON }} -m pip install *.whl"

requirements:
  build:
    - nushell
  host:
    - "python >=3.9"
    - pip
  run:
    - "python >=3.9"
    - async-timeout>=4.0.3

tests:
  - python:
      imports:
        - valkey

about:
  description: |
    conda packaging of [https://github.com/valkey-io/valkey-py](https://github.com/valkey-io/valkey-py)
  homepage: https://github.com/valkey-io/valkey-py
  repository: https://github.com/valkey-io/valkey-py
