name: tests

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - .github/renovate.json
      - .pre-commit-config.yaml
      - readme.md

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  # sleep some time before we build packages
  # channel may still processing newly uploaded package
  # give they some time,
  # so rattler-build can see packages in repodata.json
  sleep:
    runs-on: 'ubuntu-24.04'
    steps:
      - run: sleep 600

  conda:
    needs: sleep
    uses: ./.github/workflows/_build_conda.yaml

  lint:
    needs:
      - conda
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5

      - run: uv sync --locked

      - run: uv run render.py
      - run: uv run dprint fmt
      - run: git diff --exit-code

  pass:
    needs:
      - lint
      - conda
    runs-on: 'ubuntu-24.04'
    steps:
      - run: 'echo success'
