name: tests

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - .github/renovate.json
      - .pre-commit-config.yaml
      - readme.md

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  conda:
    uses: ./.github/workflows/_build_conda.yaml

  lint:
    needs:
      - conda
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c7f87aa956e4c323abf06d5dec078e358f6b4d04 # v6

      - run: uv sync --locked

      - run: uv run python scripts/render.py
      - run: uv run dprint fmt
      - run: git diff --exit-code

  pass:
    needs:
      - lint
      - conda
    runs-on: "ubuntu-24.04"
    steps:
      - run: "echo success"
